### ISSUE TITLE
Multiple Object Creation / Update Cause Error

### ISSUE THREAD

**Issue by Asayu123** [vmware/nsxramlclient#15]
When i request multiple object creation via NsxClient.create method like following code, it caused AttributeError.  

### Sample Code
`client_session = NsxClient(nsxraml_file, nsxmanager, nsx_username, nsx_password, debug=False, fail_mode="raise")`  

`target_resource = 'ipsetCreate' `  
`uri_parameters = {'scopeMoref': 'globalroot-0'}`  

`request_body = {'ipset': []} `  

`query = {
            'type': {'typeName': 'IPSet'},
            'name': "My Ipset",
            'description': "Test",
            'value': "192.168.1.0/24",
            'inheritanceAllowed': False
        }
`  
`query2 = {
            'type': {'typeName': 'IPSet2'},
            'name': "My Ipset2",
            'description': "Test2",
            'value': "192.168.2.0/24",
            'inheritanceAllowed': False
        }
`  

`request_body['ipset'].append(query)` 
`request_body['ipset'].append(query2)`   

`response = client_session.create(target_resource, uri_parameters, request_body)` 

### Caused Error
```
Traceback (most recent call last):

.... omission.....

  File "/Users/User/PycharmProjects/nsx_api/nsx_api/services/IPsetService.py", line 56, in create_IPset
    response = self.client_session.create(target_resource, uri_parameters, request_body)
  File "/Users/User/virtualenv/nsx_api/lib/python3.5/site-packages/nsxramlclient/client.py", line 104, in create
    additional_headers)
  File "/Users/User/virtualenv/nsx_api/lib/python3.5/site-packages/nsxramlclient/client.py", line 150, in _request
    request_body = xmloperations.dict_to_xml(request_body_dict)
  File "/Users/User/virtualenv/nsx_api/lib/python3.5/site-packages/nsxramlclient/xmloperations.py", line 57, in dict_to_xml
    parse_dict(xml_root_object, dict_to_parse[root_dict_key])
  File "/Users/User/virtualenv/nsx_api/lib/python3.5/site-packages/nsxramlclient/xmloperations.py", line 63, in parse_dict
    for subitem in dict_to_parse.items():
AttributeError: 'list' object has no attribute 'items'
```  

### Possible cause
parse_dict method (@xmloperations.py) presupposes that second level of request_body_dict is a dictionary object, but with multiple object, it is array.

### Question
I'm not sure that this error is caused because this library doesn't support Multiple object creation for now or it is caused by my wrong usage.  
So I'm glad if someone tell me whether this behavior is expected one or not.  
Thanks in advance.

**Comment by yfauser** [comment]
Hi @Asayu123 

sorry for the 12 days wait time. I was off for Christmas and New Year. 
It is true that nsxramlclient doesn't expect the first child object of the request_body_dict to be a list.
However I don't think I remember any case in the NSX API where the first child is a list.
Usually you have something like:

```xml
<top_level>
  <child_type>
     <child>
        <value/>
        <value/>
     </child>
     <child>
        <value/>
        <value/>
     </child>
     ....
  </child_type>
</top_level>
```
In you case of ipsets the API actually only expects one IPSet per POST as far as I know.
```
POST https://{{nsxmanager}}/api/2.0/services/ipset/{{scopeMoref}}
```
```xml
<ipset>
  <objectId></objectId>
  <type>
    <typeName></typeName>
  </type>
  <description></description>
  <name></name>
  <revision></revision>
  <objectTypeName></objectTypeName>
  <value></value>
  <inheritanceAllowed></inheritanceAllowed>
</ipset>
```
So your code could rather look something like this:
```python
client_session = NsxClient(nsxraml_file, nsxmanager, nsx_username, nsx_password, debug=True, fail_mode="raise")

target_resource = 'ipsetCreate'
uri_parameters = {'scopeMoref': 'globalroot-0'}

request_bodies = []

request_bodies.append({'ipset': {'type': {'typeName': 'IPSet'}, 'name': "My Ipset", 'description': "Test",
                                 'value': "192.168.1.0/24", 'inheritanceAllowed': False }})

request_bodies.append({'ipset': {'type': {'typeName': 'IPSet2'}, 'name': "My Ipset2", 'description': "Test2",
                                 'value': "192.168.2.0/24", 'inheritanceAllowed': False }})

for request_body in request_bodies:
    response = client_session.create(target_resource, uri_parameters, request_body)
```

**Comment by Asayu123** [comment]
Hi, @yfauser , Thank you for your response!  

I found that I mistook that NSX_API treats multiple request.  
(I saw multiple firewall rule creation example in NSX API documentation and then I mistook that NSX API supports multiple object operation. but it was single FirewallSection operation, not rule operation.)  
  
Rather than modifying library, I'll try to create multiple object by iteration like your sample code.  
  
  ...
By the way, If we issue large number of rules by 'dfwL3Rules' resource operation with iteration, It will take a lot of time at NSX Manager's processing (maybe due rule propagate process).  
Also I think that multi-thread approach will not work for speed up because it cause Etag Lock (Optimistic Lock) conflict.  

In this case, Do you think Is it a good idea to use 'dfwL3Section' operation instead of 'dfwL3Rules' operation?  

Thank you in advance!

**Comment by yfauser** [comment]
Hi @Asayu123,
yes, I agreee, using a read and update of the dfwL3Section is indeed your best bet to reduce the number of API calls you need to make.

I'm closing this issue now, but feel free to continue the discussion using this issue. We can also go on and discuss on a closed issue.

**Comment by Asayu123** [comment]
Hi, @yfauser, Thank you for your advice!  
  
I'll try that idea with large number of rule operations.  
Thank you for your kindness and time !
